name: Deno CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: todolist
        ports:
          - 5435:5432
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check
      
      - name: Run migrations
        run: deno run -A --unstable https://deno.land/x/nessie/cli.ts migrate

      - name: Run seeds
        run: deno run -A --unstable https://deno.land/x/nessie/cli.ts seed

      - name: Run tests
        run: deno test --unstable --allow-net --allow-env --allow-read --allow-write
